### ISSUE TITLE
Running on OS X Fails

### ISSUE THREAD

**Issue by bensig** [MultitudeVR/ChatCompletionsGUI#3]
Tried installing tk using `brew install python-tk` but I'm still getting this error

python chat.py         
```
Traceback (most recent call last):
  File "/Users/b/Projects/AI/ChatCompletionsGUI/chat.py", line 4, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by Vwing** [comment]
Hi Ben! Sorry I didn't get to this earlier.

Looks like it's a common issue on Mac, see https://stackoverflow.com/questions/68554782/modulenotfounderror-no-module-named-tkinter-on-macos

so just follow the top answer there (run `brew install python-tk`) and that should hopefully fix it!
